version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-named-lock
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: locktest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3333:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
